export default {
  title: "Computation Degree Zero (Placeholder)",
  urls: [],
  essay: `<p>Unlike numbers with counterparts in the natural world, the number zero refers to an empty set that eludes direct observation. Yet arithmetic originates from zero, presupposing its existence. Zero is abstraction in its purest form. The Turing machine extended mathematical abstraction into computation, utilizing the binary states of zero and one within a comprehensive and universal computational paradigm. Meanwhile, painting’s approach to abstraction emerged as a break with representational norms. Both artistic and computational abstraction are processes of reduction that turn compression and constraints into sites of productivity. Mathcastles, a studio run by two anonymous artist-programmers who explore the conceptual possibilities of the Ethereum Virtual Machine, launched a series of projects under the title “Zero Suite” in December 2022. The works in “Zero Suite” use the cryptographic technique of zero-knowledge proof technology as a method of verifying information without disclosing its content, challenging the audience to think about computational and artistic modes of abstraction together.</p>

<p>The work remains unknowable, posing an insuperable challenge to the powers of the imagination even as it incites them.</p>

<p>The 2022 deployment of “Zero Suite” contained the basic framework for pieces in the series: a digital drawing encoded in the hashed data of a Merkle tree. The work is essentially a set of public hashes that allow for the selective revealing of its contents. The first initialization of this machinery was presented in “Uncomputer,” an online exhibition curated by Grailers DAO for Unit London this past fall. Titled zero glimpse sunflower one (2023), it is a drawing that cannot be seen but whose existence can be proven through cryptography. The paradox of concealing the drawing even as its characteristics are disclosed relies on zero-knowledge proofs, a technology first developed in the 1980s. Recently, zk proofs have been increasingly used in blockchain technology, particularly in Layer 2 scaling solutions. Zk tech allows for the execution of complex computations off-chain by generating succinct proofs, which are then verified and settled on Ethereum mainnet.</p>

<p>Using zk-SNARKS, a variant of zk proofs, Mathcastles encoded the secret drawing in zero glimpse sunflower one into a secure data format. Parts of the drawing and their spatial relations can be selectively revealed alongside assertions pertaining to the work, while the work itself remains unknowable, posing an insuperable challenge to the powers of the imagination even as it incites them. While the studio has not yet executed any revelations of zero glimpse sunflower one, the second iteration of “Zero Suite,” Angelus, demonstrates how these disclosures might occur. On December 29, the smart contract was deployed, with the work’s precise price, which is set at less than 0.00001 ETH, concealed within a secret drawing.</p>

<p>The idea for creating a work that is theoretically for sale yet practically unbuyable emerged when the studio, which has not offered any works for purchase since 2021, was approached about a potential sale of zero glimpse sunflower one in the context of the “Uncomputer” exhibition. Faced with this request, Mathcastles first considered making the drawing “for sale” at a secret price, yet ultimately decided to create a separate work exclusively focused on the paradox of appropriability. The price of Angelus is encoded on a 32-by-32 array of pixels as the sum of all pixel values. Each pixel represents a value between zero and the 77-digit prime number underpinning the BN-254 curve—a mathematical equation used in zk cryptography—making the precise price virtually impossible to know. Here, the zk proof communicates the existence of the price and verifiably shows that the work could be acquired if the buyer possessed knowledge of it. This interplay of paradoxes serves as an entry point for engaging with the concept of “Zero Suite,” while simultaneously invoking questions about the relationship of price to value and the commodification of art.
A realist painting of two peasants in a field, bowing their heads in prayer over a basket of potatoesJean-Francois Millet: L’Angelus, 1857-59
A gainy black-and-white X-ray image faintly showing the outline of a small coffinX-ray of Jean-Francois Millet’s L’Angelus (1857-59)</p>

<p>The work’s title nods to the history of painting and the perception of value. Jean-François Millet’s L’Angelus (1857–59) is a painting of two peasants in a moment of contemplation, which viewers at the time interpreted as prayer during a break from work. However, an X-ray study in 1963 revealed that the basket with potatoes on the ground between the peasants was initially an infant’s coffin. It appears that Millet painted a burial scene but then converted it into a pious one, perhaps to make the work more marketable. Despite this, the work sold below Millet’s asking price; two years earlier, Millet had sold his now-famous work The Gleaners (1857) at a price so embarrassingly low that he requested it be kept secret. Hence, the Millet reference here alludes to both a hidden image and to an undisclosed price. The secrecy around the absurdly low price of Mathcastles’s Angelus might be interpreted as a suggestion that the studio views the NFT market as being as inept at appreciating value as the nineteenth-century Paris Salons.</p>

<p>This invocation of the unknowable links the works from “Zero Suite” to a lineage of artists exploring knowledge asymmetries. Marcel Duchamp’s With Hidden Noise (1916)  is a ball of twine secured with brass plates on either side, with a small, unidentified object rattling inside, placed there by the artist’s collaborator. Rhea Myers’s Secret Artwork (2018) is probably the first artwork to use blockchain technology to explore similar asymmetries. The work decouples the secret content of the work from its ownership by storing the cryptographic hash of the work in a smart contract and making it ownable as an ERC-721 token. But while Myers’s work plays with blockchain-enabled knowledge asymmetry, for Mathcastles the utilization of zk proofs is a way to engage with the theme of abstraction. The technology enables artists to maintain the anonymity of the central subject in their artwork while unveiling its abstracted features.
A list of kinds of metadata, including Ethereum address and transaction hash, encoded in wingdings, colored symbols, and emojiRhea Myers: Secret Artwork, 2018
A black-and-white photograph of abstract paintings hung salon style in the corner of a roomView of “The Last Futurist Exhibition of Paintings 0,10,” Petrograd, 1915-16</p>

<p>The emergence of abstraction in painting can be observed as a gradual abstraction from natural motifs to pure forms in works such as Piet Mondrian’s Tree (1913). After painting had gone through several phases of pure abstraction, artists like Joan Mitchell and Cy Twombly began to reintroduce floral forms in their compositions. The title of Mathcastles’s drawing suggests that it includes a sunflower motif. In recent months, abstract floral motifs have become an important feature in the artistic output of Mathcastles member 113, shared on a private Discord server. And yet, there is another, more significant way in which Mathcastles asserts the place of the work in the history of abstraction: by the invocation of “zero” itself. Modernist painting witnessed a rapid progression from the abstraction from natural motifs in 1911–13 to the absolute break with representation by the suprematists. Notably, the exhibition that premiered Malevich’s Black Square in 1915 was titled “0.10,” referencing the artists’ ambition to uncover the degree zero of painting—painting that is no longer an image of something but rather painting about nothing but itself. Liberated from the obligation to represent something other within itself, painting was free to focus on pure forms and material constituents, exceeding the scope of meaning afforded by mimetic representation. The exhibition’s reference to zero encapsulated this sense of productive freedom through reduction. The number zero is seemingly nothing—abstract, without reference and meaning, yet this nothingness contains the infinite, just as the discovery of abstraction gave painting limitless possibilities.
A digital drawing of a flower, rendered in thick strokes of blue, pink, and yellow that leave visible patterns of pixels on the black backgroundUntitled sunflower drawing by Mathcastles (2023)</p>

<p>The label of “abstract” for non-representational art reflects its evolution as an abstraction from a referential subject. In zero glimpse sunflower one and Angelus, however, zk proofs are employed in a manner that shifts the focus from a break with the mimetic referent to an abstraction of the concept of reference itself. Cryptography serves as an abstraction device on the secret drawings. It points to an understanding of art not as illusionism, materiality, or dematerialization, but as code and idea, and to an understanding of abstraction as at once computational and painterly.</p>

<p>The studio’s attempt to create works that could not exist in any other form—works that are therefore truly native to the EVM, understood as a world computer—has drawn comparisons to the modernist quest for medium specificity. However, the abstraction inherent in zero glimpse sunflower one does not fold inward to claim self-sufficiency, but instead opens outward, inviting the audience to engage with an interoperable system and to advance the code literacy already integral to Terraforms (2021), Mathcastles’s collection of 11,104 digital objects with Unicode text art that forms the base layer for a dynamically generated 3D world. If this project was already a deliberate attempt to lead the audience from the visible to the invisible, zero glimpse sunflower one radicalizes this turn away from the aesthetic surface.</p>

<p>In their approach to abstraction and randomness, Mathcastles obliquely criticizes the standardized aestheticism that has come to dominate some forms of blockchain-based generative art, which risk becoming mere ornament. The works in “Zero Suite” question whether using pseudo-random hashes as the source of entropy for generative systems limits their artistic potential. Instead of deriving emergent visual forms from hashes, Mathcastles attempts to “pierce the surface of hashes,” as 113 wrote in a post on X, to reveal their full conceptual potential. The focus here is not on the search for meaning in random visual forms, but rather on exploring distributed computation as a unique site for artistic meaning beyond the visual.</p>

<p>The focus is on exploring distributed computation as a unique site for artistic meaning beyond the visual.</p>

<p>There is, the studio’s work seems to imply, a disaccord between this technology’s state of art and the fate of art that has emerged through it. Mathcastles gestures toward an artistic use of computation where art serves as the vanguard of technology rather than being confined to standard forms. The studio’s engagement with the frontier of blockchain-based art enables the artists to raise questions about abstraction—questions that painting, in its traditional scope, has ceased to ask after it had shed the modernist legacy. The modernist quest to reveal the essence of the medium was, paradoxically, always a story about its end. Mathcastles’ work, by contrast, is inviting its audience to imagine the potential for world computer art that is yet to come.</p>

Malte Rauch serves as the head of curation at glitch Gallery in Marfa, Texas, and advises projects in the crypto and digital art space. He previously wrote about Mathcastles’ Terraforms.
`,
};
